# Generated by Django 5.2 on 2025-04-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_fitnessprofile_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fitnessprofile",
            name="dietary_preferences",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fitnessprofile",
            name="fitness_goals",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fitnessprofile",
            name="height",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fitnessprofile",
            name="phone_number",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fitnessprofile",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
