# Generated by Django 5.2 on 2025-04-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_alter_fitnessprofile_dietary_preferences_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fitnessprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
