# Generated by Django 5.2 on 2025-04-05 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_number", models.CharField(blank=True, max_length=16)),
                ("expiration_date", models.CharField(blank=True, max_length=5)),
                ("cvv", models.CharField(blank=True, max_length=4)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("card", "Credit/Debit Card"), ("paypal", "PayPal")],
                        max_length=10,
                    ),
                ),
                ("save_for_future", models.BooleanField(default=False)),
                ("subscription_active", models.BooleanField(default=False)),
                ("subscription_date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
