# Generated by Django 5.1.6 on 2025-03-16 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ingredients', models.TextField()),
                ('category', models.CharField(choices=[('protein', 'Protein'), ('carb', 'Carb'), ('fat', 'Fat'), ('vegan', 'Vegan')], max_length=100)),
                ('calories', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('strength', 'Strength'), ('cardio', 'Cardio'), ('core', 'Core'), ('flexibility', 'Flexibility')], max_length=100)),
                ('duration_minutes', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='userpreferences',
            old_name='feedback',
            new_name='dietary_restrictions',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='preferred_meals',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='preferred_workouts',
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='fitness_goal',
            field=models.CharField(blank=True, choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('maintain', 'Maintain Weight')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='preferred_meal_type',
            field=models.CharField(blank=True, choices=[('protein', 'Protein'), ('carb', 'Carb'), ('fat', 'Fat'), ('vegan', 'Vegan')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='preferred_workout_type',
            field=models.CharField(blank=True, choices=[('strength', 'Strength'), ('cardio', 'Cardio'), ('core', 'Core'), ('flexibility', 'Flexibility')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')])),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.meal')),
                ('workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.workout')),
            ],
        ),
    ]
