# Generated by Django 5.1.7 on 2025-04-02 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
                ),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("weight", models.FloatField(blank=True, null=True)),
                ("height", models.FloatField(blank=True, null=True)),
                (
                    "activity_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Sedentary", "Sedentary"),
                            ("Light", "Light Activity"),
                            ("Moderate", "Moderate Activity"),
                            ("Intense", "Intense Activity"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "fitness_goal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Weight Loss", "Weight Loss"),
                            ("Strength Building", "Strength Building"),
                            ("Endurance", "Endurance"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
