# Generated by Django 5.1.7 on 2025-03-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FitnessProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pull_ups", models.PositiveIntegerField()),
                (
                    "cardio_time",
                    models.PositiveIntegerField(help_text="Time in minutes"),
                ),
                (
                    "cool_down_time",
                    models.PositiveIntegerField(help_text="Time in minutes"),
                ),
                (
                    "sleep_hours",
                    models.PositiveIntegerField(help_text="Number of hours"),
                ),
                ("calories_burnt", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
