# Generated by Django 5.1.6 on 2025-03-16 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FitnessReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pull_ups", models.PositiveIntegerField()),
                (
                    "cardio_time",
                    models.PositiveIntegerField(help_text="Time in minutes"),
                ),
                (
                    "cool_down_time",
                    models.PositiveIntegerField(help_text="Time in minutes"),
                ),
                ("hours_of_sleep", models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="FitnessProgress",
        ),
    ]
