# Generated by Django 5.1.6 on 2025-03-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0002_fitnessreport_delete_fitnessprogress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fitnessreport",
            name="cardio_time",
            field=models.IntegerField(help_text="Time in minutes"),
        ),
        migrations.AlterField(
            model_name="fitnessreport",
            name="cool_down_time",
            field=models.IntegerField(help_text="Time in minutes"),
        ),
        migrations.AlterField(
            model_name="fitnessreport",
            name="hours_of_sleep",
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name="fitnessreport",
            name="pull_ups",
            field=models.IntegerField(),
        ),
    ]
