# Generated by Django 5.1.6 on 2025-03-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0003_alter_fitnessreport_cardio_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fitnessreport",
            name="cardio_time",
            field=models.PositiveIntegerField(help_text="Time in minutes"),
        ),
        migrations.AlterField(
            model_name="fitnessreport",
            name="cool_down_time",
            field=models.PositiveIntegerField(help_text="Time in minutes"),
        ),
        migrations.AlterField(
            model_name="fitnessreport",
            name="hours_of_sleep",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="fitnessreport",
            name="pull_ups",
            field=models.PositiveIntegerField(),
        ),
    ]
