# Generated by Django 5.2 on 2025-04-06 01:02

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0004_alter_fitnessreport_cardio_time_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fitnessreport",
            name="hours_of_sleep",
        ),
        migrations.RemoveField(
            model_name="fitnessreport",
            name="pull_ups",
        ),
        migrations.AddField(
            model_name="fitnessreport",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="fitnessreport",
            name="steps",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fitnessreport",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="fitnessreport",
            name="cardio_time",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="fitnessreport",
            name="cool_down_time",
            field=models.IntegerField(default=0),
        ),
    ]
