# Generated by Django 5.1.7 on 2025-03-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0006_fitnessreport_user_alter_fitnessreport_cardio_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fitnessreport",
            name="user",
        ),
        migrations.AlterField(
            model_name="fitnessreport",
            name="cardio_time",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="fitnessreport",
            name="cool_down_time",
            field=models.IntegerField(default=0),
        ),
    ]
