# Generated by Django 5.1.7 on 2025-03-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0009_alter_fitnessreport_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fitnessreport",
            name="user",
        ),
        migrations.AlterField(
            model_name="fitnessreport",
            name="cardio_time",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="fitnessreport",
            name="cool_down_time",
            field=models.IntegerField(default=0),
        ),
    ]
