# Generated by Django 5.2 on 2025-04-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutPlanSuggestions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='reps',
            field=models.CharField(default='8-12', max_length=20),
        ),
        migrations.AddField(
            model_name='workout',
            name='sets',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
