# Generated by Django 5.2 on 2025-04-03 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutPlanSuggestions', '0002_workout_reps_workout_sets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='fitness_goal',
            field=models.CharField(choices=[('build_muscle', 'Build Muscle'), ('lose_weight', 'Lose Weight'), ('increase_stamina', 'Increase Stamina')], max_length=50),
        ),
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Overall Recommendation', max_length=255)),
                ('rating', models.PositiveSmallIntegerField(help_text='Rate from 1 (worst) to 5 (best)')),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_recommendation_feedback', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
