# Generated by Django 5.1.6 on 2025-02-20 22:30
# Generated by Django 5.1.7 on 2025-03-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('dietary_preferences', models.CharField(max_length=100)),
                ('fitness_goals', models.CharField(max_length=100)),
            ],
        ),
    ]
