<<<<<<< HEAD
# Generated by Django 5.1.6 on 2025-02-20 22:30

=======
# Generated by Django 5.1.6 on 2025-03-15 22:31

import django.db.models.deletion
from django.conf import settings
>>>>>>> personalize-chatbot-responses
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> personalize-chatbot-responses
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='FitnessInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('dietary_preferences', models.CharField(max_length=100)),
                ('fitness_goals', models.CharField(max_length=100)),
=======
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_workouts', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_meals', models.CharField(blank=True, max_length=255, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> personalize-chatbot-responses
            ],
        ),
    ]
