# Generated by Django 5.1.7 on 2025-03-15 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("personalInfo", "0002_exercisereport"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExerciseReport",
        ),
    ]
