# Generated by Django 5.1.6 on 2025-03-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalInfo', '0004_fitnessinformation_delete_userpreferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('difficulty_level', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
