# Generated by Django 5.2 on 2025-04-03 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalInfo', '0005_workout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Workout',
        ),
    ]
