# Generated by Django 5.2 on 2025-04-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "personalInfo",
            "0007_fitnessinformation_user_alter_fitnessinformation_age_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="fitnessinformation",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
