# Generated by Django 5.2 on 2025-04-06 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("personalInfo", "0007_communitypost"),
        ("personalInfo", "0008_fitnessinformation_phone_number"),
    ]

    operations = []
