# Generated by Django 5.1.6 on 2025-04-07 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalInfo', '0009_merge_20250406_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessinformation',
            name='dietary_preferences',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitnessinformation',
            name='fitness_goals',
            field=models.TextField(blank=True, null=True),
        ),
    ]
