# Generated by Django 5.1.6 on 2025-04-07 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalInfo', '0011_alter_fitnessinformation_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunityPost',
        ),
    ]
