# Generated by Django 5.1.7 on 2025-03-22 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('dietary_restrictions', models.CharField(choices=[('vegetarian', 'Vegetarian'), ('gluten_free', 'Gluten-Free'), ('dairy_free', 'Dairy-Free'), ('none', 'No Restrictions')], max_length=50)),
                ('fitness_goals', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('energy_boost', 'Energy Boost')], max_length=50)),
                ('meal_type', models.CharField(choices=[('quick_meals', 'Quick Meals'), ('high_protein', 'High-Protein'), ('low_carb', 'Low-Carb')], max_length=50)),
                ('time_required', models.IntegerField(help_text='Time required in minutes')),
                ('budget', models.DecimalField(decimal_places=2, help_text='Cost in CAD', max_digits=5)),
                ('instructions', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealSuggestions.meal')),
            ],
            options={
                'unique_together': {('user', 'meal')},
            },
        ),
    ]
